spring:
  datasource:
    url: jdbc:mysql://111.231.138.140:3306/project
    username: project
    password: project123
    driver-class-name: com.mysql.cj.jdbc.Driver
my:
  redis:
    port: 6379
    host-name: 192.168.220.120
    password: Wj123456
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.my.project.dao